# From https://github.com/gudzpoz/luajava/blob/main/.github/workflows/build-natives.yml
# Modified from https://github.com/libgdx/libgdx/blob/master/.github/workflows/build-publish.yml
# LastModify: chenchao 

name: Build binaries

on:
  workflow_dispatch:

jobs:
  build_luajit_library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - run: echo "JAVA_8=$JAVA_HOME" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - run: echo "JAVA_11=$JAVA_HOME" >> $GITHUB_ENV

      - name: Clone LuaJIT repository
        run: git clone https://github.com/LuaJIT/LuaJIT.git

      - name: Checkout tag v2.1
        run: |
           cd LuaJIT                   # 进入克隆的仓库目录
           git checkout v2.1   # 切换到指定 Tag
           cd ..
           ls

      - name: Install cross-compilation toolchains
        run: |
          sudo apt update
          sudo apt install -y --force-yes gcc g++ linux-libc-dev libc6-dev
          sudo apt install -y --force-yes libc6-dev-i386 lib32stdc++-9-dev
          sudo apt install -y --force-yes linux-libc-dev linux-libc-dev-i386-cross
          sudo apt install -y --force-yes linux-libc-dev-armhf-cross linux-libc-dev-arm64-cross linux-libc-dev-amd64-cross
          sudo apt install -y --force-yes libstdc++-9-dev-i386-cross libstdc++-9-dev-arm64-cross libstdc++-9-dev-armhf-cross
          sudo apt install -y --force-yes gcc-i686-linux-gnu g++-i686-linux-gnu libc6-dev-i386-cross
          sudo apt install -y --force-yes gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross
          sudo apt install -y --force-yes gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Build natives
        run: |
          export NDK_HOME=$ANDROID_NDK_LATEST_HOME
          sh build.sh

      - name: Copy header files
        run: |
          mkdir -p opt/includes
          cp -f luajit/src/*.h opt/includes

      - run: echo "DATA=$( date +"%Y-%m-%d-%H-%M" )" >> $GITHUB_ENV

      - name: Zip files
        run:  zip -r ${{ env.DATA }}.zip opt

      - name: List files
        run: |
          pwd
          tree -a

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATA }}
          files: ${{ env.DATA }}.zip
